# fly.toml app configuration file generated for healthify on 2024-01-06T18:55:49+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "healthify"
primary_region = "syd"

[build]
PORT=3000

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
