GET http://localhost:3001/api/user

###
POST http://localhost:3001/api/user
Content-Type: application/json

{
  "name": "Annie"
}

###
PUT http://localhost:3001/api/user/6852
Content-Type: application/json

{
  "smoke": 1
}

###
GET http://localhost:3001/api/user/6852